// Player data for Dinger. Each player.clues array has exactly 7 items,
// hand-ordered from vaguest to most identifying:
//   [0-2] broad facts that could describe many players
//   [3-5] moderate reveals (team, role, nickname)
//   [6]   the single most identifying fact (career total, record, signature moment)
// game.js interleaves these with 3 auto-generated era clues (decade window,
// start year, end year) to build the full 10-clue ladder.
// Clues never contain any part of the player's own name.
const PLAYERS = [
  {
    id: 'bonds',
    name: 'Barry Bonds',
    accept: ['barry bonds', 'bonds'],
    era: '1986–2007',
    clues: ['Left-handed slugger', 'California roots', 'Famous baseball family', 'Started with Pirates', 'Giants left fielder', 'Seven MVP awards', 'All-time home run leader'],
  },
  {
    id: 'ruth',
    name: 'Babe Ruth',
    accept: ['babe ruth', 'ruth', 'the bambino'],
    era: '1914–1935',
    clues: ['Left-handed slugger', 'Started as a pitcher', 'Baltimore childhood', 'Sold by Boston', 'Yankees legend', 'Sultan of Swat nickname', '714 career homers'],
  },
  {
    id: 'aaron',
    name: 'Hank Aaron',
    accept: ['hank aaron', 'henry aaron', 'aaron', 'hammerin hank'],
    era: '1954–1976',
    clues: ['Right-handed slugger', 'Born in Mobile', 'Braves icon', 'Played in Milwaukee and Atlanta', 'Faced hate mail', 'Hammer nickname', 'Longtime home run king with 755 homers'],
  },
  {
    id: 'jeter',
    name: 'Derek Jeter',
    accept: ['derek jeter', 'jeter', 'the captain'],
    era: '1995–2014',
    clues: ['Michigan roots', 'Yankees draft pick', 'Shortstop leader', 'October regular', 'Famous flip play', 'Team captain', '3,000-hit club, number 2 retired'],
  },
  {
    id: 'rivera',
    name: 'Mariano Rivera',
    accept: ['mariano rivera', 'rivera', 'mo', 'the sandman'],
    era: '1995–2013',
    clues: ['Panama native', 'Relief pitcher', 'Yankees closer', 'One famous pitch', 'Cutter master', 'Enter Sandman entrance', '652 career saves, last player wearing 42'],
  },
  {
    id: 'griffey',
    name: 'Ken Griffey Jr.',
    accept: ['ken griffey jr', 'ken griffey', 'griffey', 'junior', 'the kid'],
    era: '1989–2010',
    clues: ['Sweet lefty swing', 'Father played MLB', 'Seattle superstar', 'Backward cap', 'Center-field wall catches', 'The Kid nickname', '630 career homers, number 24 Mariners icon'],
  },
  {
    id: 'ripken',
    name: 'Cal Ripken Jr.',
    accept: ['cal ripken jr', 'cal ripken', 'ripken', 'the iron man'],
    era: '1981–2001',
    clues: ['Maryland roots', 'Tall shortstop', 'Orioles lifer', 'Moved to third base', 'Iron Man nickname', 'Consecutive games streak', '2,632 straight games, passed Gehrig'],
  },
  {
    id: 'ryan',
    name: 'Nolan Ryan',
    accept: ['nolan ryan', 'ryan', 'the ryan express'],
    era: '1966–1993',
    clues: ['Texas fireballer', 'Very long career', 'Fastball legend', 'Express nickname', 'Astros and Rangers years', 'Famous headlock fight', 'Most career strikeouts with 5,714'],
  },
  {
    id: 'mays',
    name: 'Willie Mays',
    accept: ['willie mays', 'mays', 'the say hey kid'],
    era: '1951–1973',
    clues: ['Alabama roots', 'Negro leagues start', 'Giants center fielder', 'Say Hey nickname', 'Polo Grounds star', 'Famous over-the-shoulder catch', '660 career homers, all-time center-field great'],
  },
  {
    id: 'mantle',
    name: 'Mickey Mantle',
    accept: ['mickey mantle', 'mantle', 'the mick', 'the commerce comet'],
    era: '1951–1968',
    clues: ['Switch-hitting slugger', 'Oklahoma hometown', 'Yankees center fielder', 'Knee injuries', 'The Mick nickname', '1956 Triple Crown', '536 career homers, Yankees dynasty star'],
  },
  {
    id: 'williams',
    name: 'Ted Williams',
    accept: ['ted williams', 'williams', 'teddy ballgame', 'the splendid splinter'],
    era: '1939–1960',
    clues: ['Military pilot', 'Loved fishing', 'Red Sox left fielder', 'Splendid Splinter nickname', 'Defenses shifted against him', 'Last .400 hitter', '.406 season, 521 career homers'],
  },
  {
    id: 'robinson',
    name: 'Jackie Robinson',
    accept: ['jackie robinson', 'robinson', 'jackie'],
    era: '1947–1956',
    clues: ['Georgia birthplace', 'UCLA athlete', 'Army court-martial', 'Signed by Branch Rickey', 'Brooklyn Dodger', 'Broke color barrier', 'Number 42 retired league-wide, MLB celebrates his day'],
  },
  {
    id: 'koufax',
    name: 'Sandy Koufax',
    accept: ['sandy koufax', 'koufax'],
    era: '1955–1966',
    clues: ['Brooklyn lefty', 'Big curveball', 'Dodgers ace', 'Dominant 1960s peak', 'Yom Kippur decision', 'Perfect game', 'Three Cy Youngs, retired young at his peak'],
  },
  {
    id: 'rose',
    name: 'Pete Rose',
    accept: ['pete rose', 'rose', 'charlie hustle'],
    era: '1963–1986',
    clues: ['Switch hitter', 'Headfirst slides', 'Cincinnati icon', 'Charlie Hustle nickname', 'Big Red Machine', 'Player-manager', '4,256 career hits, MLB hit king'],
  },
  {
    id: 'jackson',
    name: 'Reggie Jackson',
    accept: ['reggie jackson', 'jackson', 'mr october'],
    era: '1967–1987',
    clues: ['Right-field power', 'Big strikeout totals', 'Oakland slugger', 'Yankees star', 'Had a candy bar named after him', 'Mr. October nickname', 'Three homers in one World Series game'],
  },
  {
    id: 'ortiz',
    name: 'David Ortiz',
    accept: ['david ortiz', 'ortiz', 'big papi', 'papi'],
    era: '1997–2016',
    clues: ['Dominican slugger', 'Started with Twins', 'Red Sox designated hitter', 'Big Papi nickname', 'Fenway favorite', '2004 curse breaker', '541 career homers, World Series MVP'],
  },
  {
    id: 'johnson',
    name: 'Randy Johnson',
    accept: ['randy johnson', 'johnson', 'the big unit'],
    era: '1988–2009',
    clues: ['Very tall pitcher', 'Left-handed ace', 'Devastating slider', 'Mariners breakout', 'Diamondbacks champion', 'Big Unit nickname', '4,875 strikeouts, threw a perfect game'],
  },
  {
    id: 'maddux',
    name: 'Greg Maddux',
    accept: ['greg maddux', 'maddux', 'the professor', 'mad dog'],
    era: '1986–2008',
    clues: ['Known for glasses', 'Command specialist', 'Started with Cubs', 'Braves rotation star', 'Professor nickname', 'Four straight Cy Youngs', '355 career wins, 18 Gold Gloves'],
  },
  {
    id: 'gwynn',
    name: 'Tony Gwynn',
    accept: ['tony gwynn', 'gwynn', 'mr padre'],
    era: '1982–2001',
    clues: ['College basketball player', 'Contact hitting master', 'San Diego lifer', 'Padres right fielder', 'Studied video constantly', 'Eight batting titles', '.338 career average, 3,000-hit club'],
  },
  {
    id: 'ichiro',
    name: 'Ichiro Suzuki',
    accept: ['ichiro suzuki', 'ichiro', 'suzuki'],
    era: '2001–2019',
    clues: ['Japanese star', 'Slap-hitting style', 'Right-field defense', 'Orix beginning', 'Seattle arrival', 'Rookie and MVP same year', '262-hit season, 3,000 MLB hits'],
  },
  {
    id: 'gehrig',
    name: 'Lou Gehrig',
    accept: ['lou gehrig', 'gehrig', 'the iron horse'],
    era: '1923–1939',
    clues: ['Columbia student', 'Yankees first baseman', 'Murderers Row bat', 'Iron Horse nickname', 'Consecutive games streak', 'Luckiest man speech', '2,130 straight games, number 4 retired'],
  },
  {
    id: 'wagner',
    name: 'Honus Wagner',
    accept: ['honus wagner', 'wagner', 'the flying dutchman'],
    era: '1897–1917',
    clues: ['Dead-ball era star', 'Bowlegged runner', 'Pirates shortstop', 'Flying Dutchman nickname', 'Eight batting titles', 'Famous T206 card', '3,420 career hits, early shortstop great'],
  },
  {
    id: 'young',
    name: 'Cy Young',
    accept: ['cy young', 'young'],
    era: '1890–1911',
    clues: ['19th-century pitcher', 'Right-handed workhorse', 'Cleveland Spiders', 'Cyclone nickname', 'Played for Boston too', 'Perfect game', 'Most career wins with 511, award named after him'],
  },
  {
    id: 'mathewson',
    name: 'Christy Mathewson',
    accept: ['christy mathewson', 'mathewson', 'big six'],
    era: '1900–1916',
    clues: ['Bucknell athlete', 'Known as a gentleman', 'New York Giants ace', 'Fadeaway pitch', 'Three shutouts in 1905 Series', 'Big Six nickname', '373 career wins, inaugural Hall class'],
  },
  {
    id: 'hornsby',
    name: 'Rogers Hornsby',
    accept: ['rogers hornsby', 'hornsby', 'rajah'],
    era: '1915–1937',
    clues: ['Right-handed hitter', 'Fiery personality', 'Second baseman', 'Cardinals star', 'Rajah nickname', 'Two Triple Crowns', '.424 season, .358 career average'],
  },
  {
    id: 'musial',
    name: 'Stan Musial',
    accept: ['stan musial', 'musial', 'stan the man'],
    era: '1941–1963',
    clues: ['Pennsylvania-born hitter', 'Left-handed line-drive hitter', 'Outfielder and first baseman', 'Cardinals icon', 'The Man nickname', 'Three MVP awards', '3,630 career hits, seven batting titles'],
  },
  {
    id: 'berra',
    name: 'Yogi Berra',
    accept: ['yogi berra', 'berra', 'yogi'],
    era: '1946–1965',
    clues: ['Famous quotes', 'Yankees catcher', 'Great catcher and manager', 'Managed both New York teams', 'Caught a perfect game', 'Ten World Series rings', 'Number 8 retired, famous "not over" quote'],
  },
  {
    id: 'bench',
    name: 'Johnny Bench',
    accept: ['johnny bench', 'bench'],
    era: '1967–1983',
    clues: ['Oklahoma catcher', 'Huge hands', 'Cincinnati star', 'Big Red Machine', 'One-handed catching style', 'Two MVP awards', 'Ten Gold Gloves, 389 career homers'],
  },
  {
    id: 'clemente',
    name: 'Roberto Clemente',
    accept: ['roberto clemente', 'clemente'],
    era: '1955–1972',
    clues: ['Puerto Rican star', 'Powerful throwing arm', 'Pirates right fielder', 'Four batting titles', 'Humanitarian legacy', 'Nicaragua relief flight', 'Exactly 3,000 hits, died in a plane crash'],
  },
  {
    id: 'paige',
    name: 'Satchel Paige',
    accept: ['satchel paige', 'paige'],
    era: '1926–1965',
    clues: ['Showman style', 'Negro leagues pitcher', 'Famous age mystery', 'Kansas City Monarchs', 'Hesitation pitch', 'Cleveland MLB debut', 'Oldest MLB rookie, pitched into his fifties'],
  },
  {
    id: 'joshgibson',
    name: 'Josh Gibson',
    accept: ['josh gibson'],
    era: '1930–1946',
    clues: ['Negro leagues slugger', 'Catcher with huge power', 'Legendary long homers', 'Homestead Grays', 'Pittsburgh Crawfords', 'Called the Black Babe Ruth', 'Posthumous Hall selection, MLB records updated later'],
  },
  {
    id: 'henderson',
    name: 'Rickey Henderson',
    accept: ['rickey henderson', 'henderson', 'man of steal'],
    era: '1979–2003',
    clues: ['Leadoff hitter', 'Talked in third person', 'Oakland speedster', 'Athletics superstar', 'Man of Steal nickname', '130 steals in a season', 'All-time runs and steals leader, 1,406 career steals'],
  },
  {
    id: 'brett',
    name: 'George Brett',
    accept: ['george brett', 'brett'],
    era: '1973–1993',
    clues: ['Left-handed hitter', 'Sweet swing', 'Third baseman', 'Royals lifer', '.390 chase', 'Pine tar game', '3,154 career hits, 1985 champion'],
  },
  {
    id: 'schmidt',
    name: 'Mike Schmidt',
    accept: ['mike schmidt', 'schmidt'],
    era: '1972–1989',
    clues: ['Power and defense', 'Booed by home fans', 'Phillies third baseman', 'Ten Gold Gloves', 'Three MVP awards', '1980 champion', '548 career homers, all-time great third baseman'],
  },
  {
    id: 'ozzie',
    name: 'Ozzie Smith',
    accept: ['ozzie smith', 'the wizard'],
    era: '1978–1996',
    clues: ['Defensive wizard', 'Switch hitter', 'Cardinals shortstop', 'Backflip entrance', '13 Gold Gloves', 'The Wizard nickname', '1985 walk-off homer, Hall of Fame glove'],
  },
  {
    id: 'boggs',
    name: 'Wade Boggs',
    accept: ['wade boggs', 'boggs'],
    era: '1982–1999',
    clues: ['Contact hitter', 'Superstitious reputation', 'Red Sox third baseman', 'Chicken routine', 'Later Yankee champion', 'Horseback victory lap', '.328 career average, 3,010 hits'],
  },
  {
    id: 'thomas',
    name: 'Frank Thomas',
    accept: ['frank thomas', 'the big hurt'],
    era: '1990–2008',
    clues: ['Football background', 'Massive right-handed hitter', 'Auburn athlete', 'White Sox slugger', 'Big Hurt nickname', 'Back-to-back MVPs', '521 career homers, huge on-base numbers'],
  },
  {
    id: 'chipper',
    name: 'Chipper Jones',
    accept: ['chipper jones', 'chipper'],
    era: '1993–2012',
    clues: ['Switch hitter', 'First overall pick', 'Braves third baseman', 'Atlanta dynasty piece', 'Crushed Mets pitching', '1999 MVP', '468 career homers, Larry was his real first name'],
  },
  {
    id: 'clemens',
    name: 'Roger Clemens',
    accept: ['roger clemens', 'clemens', 'the rocket'],
    era: '1984–2007',
    clues: ['Texas power pitcher', '20-strikeout games', 'Red Sox ace', 'Rocket nickname', 'Blue Jays rebound', 'Yankees and Astros years', 'Seven Cy Youngs, 354 career wins'],
  },
  {
    id: 'pedro',
    name: 'Pedro Martinez',
    accept: ['pedro martinez', 'martinez', 'pedro'],
    era: '1992–2009',
    clues: ['Small frame', 'Dominican ace', 'Expos breakout', 'Red Sox legend', 'Yankee Stadium chant', 'Famous Zimmer incident', 'Three Cy Youngs, 2000 ERA of 1.74'],
  },
  {
    id: 'arod',
    name: 'Alex Rodriguez',
    accept: ['alex rodriguez', 'a-rod', 'arod'],
    era: '1994–2016',
    clues: ['First overall pick', 'Seattle shortstop', 'Rangers mega-contract', 'Yankees third baseman', 'A-Rod nickname', 'Biogenesis suspension', '696 career homers, three MVP awards'],
  },
  {
    id: 'manny',
    name: 'Manny Ramirez',
    accept: ['manny ramirez', 'ramirez', 'manny'],
    era: '1993–2011',
    clues: ['Quirky personality', 'Unpredictable superstar persona', 'Cleveland slugger', 'Red Sox left fielder', 'Green Monster home runs', 'High-five cutoff play', '555 career homers, postseason RBI machine'],
  },
  {
    id: 'thome',
    name: 'Jim Thome',
    accept: ['jim thome', 'thome'],
    era: '1991–2012',
    clues: ['Gentle reputation', 'Pointed bat before pitches', 'Cleveland power bat', 'First baseman and DH', 'Very high strikeouts', 'Played for five teams', '612 career homers, Hall of Fame slugger'],
  },
  {
    id: 'pujols',
    name: 'Albert Pujols',
    accept: ['albert pujols', 'pujols', 'the machine'],
    era: '2001–2022',
    clues: ['Dominican-born slugger', 'The Machine nickname', 'Cardinals first baseman', 'Three MVP awards', '2006 champion', 'Angels contract', '703 career homers, 3,000-hit club'],
  },
  {
    id: 'guerrero',
    name: 'Vladimir Guerrero',
    accept: ['vladimir guerrero', 'guerrero', 'vlad'],
    era: '1996–2011',
    clues: ['Free-swinging hitter', 'Huge throwing arm', 'Dominican right fielder', 'Expos star', 'Often batted gloveless', 'Famous bad-ball hitter', '2004 AL MVP, Vlad nickname'],
  },
  {
    id: 'pudge',
    name: 'Ivan Rodriguez',
    accept: ['ivan rodriguez', 'pudge', 'pudge rodriguez'],
    era: '1991–2011',
    clues: ['Elite throwing arm', 'Puerto Rican catcher', 'Texas Rangers star', 'Pudge nickname', '1999 MVP', 'Marlins champion', '13 Gold Gloves, most games caught by a catcher'],
  },
  {
    id: 'fernando',
    name: 'Fernando Valenzuela',
    accept: ['fernando valenzuela', 'valenzuela', 'fernando'],
    era: '1980–1997',
    clues: ['Looked skyward during delivery', 'Screwball specialist', 'Mexican lefty', 'Dodgers phenomenon', 'Rookie-year craze', 'Rookie of the Year', 'Cy Young same season, 1981 champion'],
  },
  {
    id: 'trout',
    name: 'Mike Trout',
    accept: ['mike trout', 'trout'],
    era: '2011–present',
    clues: ['Loves weather reports', 'Five-tool star', 'New Jersey hometown', 'Angels center fielder', 'Limited playoff appearances', 'Three MVP awards', 'Generational WAR totals, Millville Meteor nickname'],
  },
  {
    id: 'kershaw',
    name: 'Clayton Kershaw',
    accept: ['clayton kershaw', 'kershaw'],
    era: '2008–present',
    clues: ['Big curveball', 'Charity work in Zambia', 'Dallas lefty', 'Dodgers ace', 'Regular-season dominance', 'Postseason scrutiny', 'Three Cy Youngs, 2020 champion'],
  },
  {
    id: 'ohtani',
    name: 'Shohei Ohtani',
    accept: ['shohei ohtani', 'ohtani'],
    era: '2018–present',
    clues: ['Pitcher and hitter', 'Compared to Ruth', 'Japanese two-way star', 'Angels debut', 'Famous dog named Decoy', 'Unanimous MVP seasons', '50-50 season, Dodgers mega-deal'],
  },
  {
    id: 'judge',
    name: 'Aaron Judge',
    accept: ['aaron judge', 'judge'],
    era: '2016–present',
    clues: ['Very tall outfielder', 'Towering home runs', 'Yankees right fielder', 'Right-field fan section', 'Team captain', 'Chased Roger Maris', '62-homer season, AL home run record'],
  },
  {
    id: 'betts',
    name: 'Mookie Betts',
    accept: ['mookie betts', 'betts', 'mookie'],
    era: '2014–present',
    clues: ['Elite bowler', 'Tennessee athlete', 'Red Sox right fielder', '2018 MVP', 'Boston champion', 'Blockbuster Dodgers trade', 'Played right field and shortstop, modern five-tool star'],
  },
  {
    id: 'harper',
    name: 'Bryce Harper',
    accept: ['bryce harper', 'harper'],
    era: '2012–present',
    clues: ['Flashy eye black', 'Teen cover star', 'Nationals phenom', 'Chosen One label', 'Right-field power', 'Two MVP awards', 'Phillies leader, moved to first base'],
  },
  {
    id: 'freeman',
    name: 'Freddie Freeman',
    accept: ['freddie freeman', 'freeman'],
    era: '2010–present',
    clues: ['Left-handed hitter', 'Canadian roots', 'Braves first baseman', '2020 MVP', 'Emotional Atlanta exit', 'Dodgers star', 'World Series walk-off grand slam'],
  },
  {
    id: 'degrom',
    name: 'Jacob deGrom',
    accept: ['jacob degrom', 'degrom'],
    era: '2014–present',
    clues: ['Former college shortstop', 'Long hair era', 'Mets right-hander', 'Little run support', 'Historically low ERA peak', '100-mph starter', 'Back-to-back Cy Youngs, Rangers contract'],
  },
  {
    id: 'puckett',
    name: 'Kirby Puckett',
    accept: ['kirby puckett', 'puckett'],
    era: '1984–1995',
    clues: ['Stocky build', 'Explosive hitter', 'Minnesota center fielder', 'Beloved Twin', 'Two World Series titles', '1991 walk-off homer', 'Glaucoma ended his career, Game 6 hero'],
  },
  {
    id: 'yount',
    name: 'Robin Yount',
    accept: ['robin yount', 'yount'],
    era: '1974–1993',
    clues: ['Debuted at 18', 'Quiet superstar', 'Milwaukee Brewer', 'Started at shortstop', 'Moved to outfield', 'MVP at two positions', '3,142 career hits, two-time MVP'],
  },
  {
    id: 'murray',
    name: 'Eddie Murray',
    accept: ['eddie murray', 'murray', 'steady eddie'],
    era: '1977–1997',
    clues: ['Switch hitter', 'Quiet superstar', 'Orioles first baseman', 'Steady nickname', 'Later Dodgers and Mets', '500-homer club', '3,000-hit club, 504 career homers'],
  },
  {
    id: 'eckersley',
    name: 'Dennis Eckersley',
    accept: ['dennis eckersley', 'eckersley', 'eck'],
    era: '1975–1998',
    clues: ['Started as a starter', 'Threw a no-hitter', 'Converted to closer', 'Oakland Athletics star', 'Low three-quarter delivery', 'Gave up a famous 1988 World Series homer', '1992 MVP and Cy Young, 390 career saves'],
  },
  {
    id: 'bobgibson',
    name: 'Bob Gibson',
    accept: ['bob gibson'],
    era: '1959–1975',
    clues: ['Also played basketball', 'Intimidating mound presence', 'Omaha native', 'Cardinals ace', 'Harlem Globetrotters link', '1968 pitching season', '1.12 ERA, two Cy Youngs'],
  },
  {
    id: 'seaver',
    name: 'Tom Seaver',
    accept: ['tom seaver', 'seaver', 'tom terrific'],
    era: '1967–1986',
    clues: ['Powerful drop-and-drive delivery', 'California right-hander', 'Mets franchise ace', 'Terrific nickname', 'Miracle Mets leader', 'Three Cy Youngs', '311 career wins, 1969 champion'],
  },
  {
    id: 'piazza',
    name: 'Mike Piazza',
    accept: ['mike piazza', 'piazza'],
    era: '1992–2007',
    clues: ['Late draft pick', 'Catcher with elite bat', 'Dodgers debut', 'Mets superstar', 'Post-9/11 home run', '396 homers as a catcher', '427 career homers, all-time slugging catcher'],
  },
  {
    id: 'molitor',
    name: 'Paul Molitor',
    accept: ['paul molitor', 'molitor', 'the ignitor'],
    era: '1978–1998',
    clues: ['Played all over the infield', 'Minnesota native', 'Brewers star', 'The Ignitor nickname', 'Designated hitter later', '39-game hitting streak', '3,319 career hits, 1993 World Series MVP'],
  },
  {
    id: 'sosa',
    name: 'Sammy Sosa',
    accept: ['sammy sosa', 'sosa', 'slammin sammy'],
    era: '1989–2007',
    clues: ['Home run hop', 'Dominican right fielder', 'Cubs slugger', 'Slammin nickname', '1998 home run race', 'Three 60-homer seasons', '609 career homers, 1998 NL MVP'],
  },
  {
    id: 'mcgwire',
    name: 'Mark McGwire',
    accept: ['mark mcgwire', 'mcgwire', 'big mac'],
    era: '1986–2001',
    clues: ['Tall first baseman', 'Oakland Bash Brother', 'Cardinals slugger later', 'Big Mac nickname', '1998 home run race', 'Broke the Maris record', '70-homer season, 583 career homers'],
  },
  {
    id: 'verlander',
    name: 'Justin Verlander',
    accept: ['justin verlander', 'verlander'],
    era: '2005–present',
    clues: ['High fastball late in games', 'Virginia right-hander', 'Tigers ace', 'No-hitter collector', 'MVP as a pitcher', 'Astros champion', 'Three Cy Youngs, World Series ring in Houston'],
  },
  {
    id: 'scherzer',
    name: 'Max Scherzer',
    accept: ['max scherzer', 'scherzer', 'mad max'],
    era: '2008–present',
    clues: ['Different colored eyes', 'Mad nickname', 'Missouri right-hander', 'Nationals ace', '20-strikeout game', 'Two no-hitters', 'Three Cy Youngs, 2019 champion'],
  },
  {
    id: 'cabrera',
    name: 'Miguel Cabrera',
    accept: ['miguel cabrera', 'cabrera', 'miggy'],
    era: '2003–2023',
    clues: ['Opposite-field power', 'Venezuelan slugger', 'Marlins debut', 'Tigers first baseman', 'Miggy nickname', '2012 Triple Crown', '500-homer and 3,000-hit club, two MVP awards'],
  },
  {
    id: 'posey',
    name: 'Buster Posey',
    accept: ['buster posey', 'posey'],
    era: '2009–2021',
    clues: ['Georgia catcher', 'Florida State star', 'Giants cornerstone', 'Rookie of the Year', 'Home-plate collision changed the rules', '2012 NL MVP', 'Three championships, modern franchise catcher'],
  },
  {
    id: 'larkin',
    name: 'Barry Larkin',
    accept: ['barry larkin', 'larkin'],
    era: '1986–2004',
    clues: ['Local college star', 'Speed and defense', 'Cincinnati shortstop', 'Reds lifer', '1990 champion', '1995 NL MVP', '12-time All-Star, Hall of Fame shortstop'],
  },
  {
    id: 'smoltz',
    name: 'John Smoltz',
    accept: ['john smoltz', 'smoltz'],
    era: '1988–2009',
    clues: ['Electric slider', 'Starter and closer', 'Michigan right-hander', 'Braves rotation pillar', '1996 Cy Young', '200-plus wins', '150-plus saves, rare hybrid pitching career'],
  },
  {
    id: 'glavine',
    name: 'Tom Glavine',
    accept: ['tom glavine', 'glavine'],
    era: '1987–2008',
    clues: ['Drafted in two sports', 'Worked the outside corner', 'Massachusetts lefty', 'Braves control artist', 'Two Cy Youngs', '1995 World Series MVP', '305 career wins, Hall of Fame command pitcher'],
  },
  {
    id: 'mccovey',
    name: 'Willie McCovey',
    accept: ['willie mccovey', 'mccovey', 'stretch'],
    era: '1959–1980',
    clues: ['Left-handed slugger', 'Towering height at first base', 'Alabama-born first baseman', 'San Francisco first baseman', 'Stretch nickname', '1969 NL MVP', '521 career homers, cove named after him'],
  },
  {
    id: 'banks',
    name: 'Ernie Banks',
    accept: ['ernie banks', 'banks', 'mr cub'],
    era: '1953–1971',
    clues: ['Famously sunny disposition', 'Play-two enthusiasm catchphrase', 'Chicago shortstop turned first baseman', 'Negro leagues start', 'Mr. Cub nickname', 'Back-to-back MVP awards', '512 career homers, never played in a postseason'],
  },
  {
    id: 'snider',
    name: 'Duke Snider',
    accept: ['duke snider', 'snider'],
    era: '1947–1964',
    clues: ['Left-handed center fielder', 'One of three iconic New York center fielders', 'Los Angeles-born but a Brooklyn star', 'Dodgers slugger', 'Duke of Flatbush nickname', 'Power bat in Ebbets Field', 'Four homers in a single World Series, subject of a famous baseball song'],
  },
  {
    id: 'campanella',
    name: 'Roy Campanella',
    accept: ['roy campanella', 'campanella', 'campy'],
    era: '1948–1957',
    clues: ['Negro leagues background', 'Italian and Black heritage', 'Brooklyn catcher', 'Three-time NL MVP', 'Campy nickname', 'Car accident ended his career', 'Paralyzed after a 1958 crash, number 39 retired'],
  },
  {
    id: 'yaz',
    name: 'Carl Yastrzemski',
    accept: ['carl yastrzemski', 'yastrzemski', 'yaz'],
    era: '1961–1983',
    clues: ['Left-handed hitter', 'Long Island roots', 'Boston left fielder', 'Followed a legend in left field', 'Yaz nickname', '1967 Triple Crown', '3,000-hit and 400-homer club, last AL Triple Crown winner for decades'],
  },
  {
    id: 'kaline',
    name: 'Al Kaline',
    accept: ['al kaline', 'kaline', 'mr tiger'],
    era: '1953–1974',
    clues: ['Signed straight from high school', 'Gold Glove defender', 'Baltimore childhood', 'Detroit right fielder', 'Mr. Tiger nickname', 'Youngest batting champion at the time', '3,000-hit club, never played a minor league game'],
  },
  {
    id: 'killebrew',
    name: 'Harmon Killebrew',
    accept: ['harmon killebrew', 'killebrew', 'killer'],
    era: '1954–1975',
    clues: ['Right-handed slugger', 'Idaho roots', 'Washington Senators start', 'Followed the team to Minnesota', 'Killer nickname', 'Rumored silhouette for a league logo', '573 career homers, 1969 AL MVP'],
  },
  {
    id: 'feller',
    name: 'Bob Feller',
    accept: ['bob feller', 'feller', 'rapid robert'],
    era: '1936–1956',
    clues: ['Debuted as a teenager', 'Iowa farm upbringing', 'Cleveland fireballer', 'Missed years for military service', 'Rapid Robert nickname', 'Opening Day no-hitter', 'Three career no-hitters, wartime Navy veteran ace'],
  },
  {
    id: 'spahn',
    name: 'Warren Spahn',
    accept: ['warren spahn', 'spahn'],
    era: '1942–1965',
    clues: ['Left-handed workhorse', 'High leg-kick delivery', 'Buffalo upbringing', 'Braves franchise ace', 'Missed years for World War II service', 'Bronze Star recipient', 'Most wins ever by a left-hander with 363'],
  },
  {
    id: 'ford',
    name: 'Whitey Ford',
    accept: ['whitey ford', 'ford', 'the chairman of the board'],
    era: '1950–1967',
    clues: ['Left-handed control artist', 'New York City native', 'Yankees rotation ace', 'Chairman of the Board nickname', 'Best postseason winning percentage of his era', '1961 Cy Young winner', 'Long scoreless World Series innings streak, 236 career wins'],
  },
  {
    id: 'carlton',
    name: 'Steve Carlton',
    accept: ['steve carlton', 'carlton', 'lefty'],
    era: '1965–1988',
    clues: ['Left-handed strikeout artist', 'Miami upbringing', 'Traded from Cardinals to Phillies', 'Devastating slider', 'Lefty nickname', 'Avoided media interviews for years', 'Four Cy Young awards, 329 career wins'],
  },
  {
    id: 'winfield',
    name: 'Dave Winfield',
    accept: ['dave winfield', 'winfield'],
    era: '1973–1995',
    clues: ['Drafted in multiple pro sports', 'Minnesota native', 'San Diego debut', 'Yankees big-money signing', 'Owner conflict overshadowed his peak', 'Toronto World Series champion', '3,000-hit and 400-homer club'],
  },
  {
    id: 'dawson',
    name: 'Andre Dawson',
    accept: ['andre dawson', 'dawson', 'the hawk'],
    era: '1976–1996',
    clues: ['Bad knees from years on turf', 'Miami-born outfielder', 'Montreal debut', 'The Hawk nickname', 'Signed a blank contract with the Cubs', '1987 NL MVP on a last-place team', '400 homers and 300 steals club'],
  },
  {
    id: 'sandberg',
    name: 'Ryne Sandberg',
    accept: ['ryne sandberg', 'sandberg', 'ryno'],
    era: '1981–1997',
    clues: ['Spokane native', 'Traded to Chicago as a throw-in', 'Chicago second baseman', 'Ryno nickname', 'Famous walk-off game vs the Cardinals', '1984 NL MVP', 'Nine Gold Gloves, long errorless-games streak at second'],
  },
  {
    id: 'palmer',
    name: 'Jim Palmer',
    accept: ['jim palmer', 'palmer'],
    era: '1965–1984',
    clues: ['Adopted as an infant', 'High leg-kick delivery', 'Baltimore right-hander', 'Never allowed a grand slam', 'Three Cy Young awards', 'Eight 20-win seasons', 'Underwear model later in life, 268 career wins'],
  },
  {
    id: 'fingers',
    name: 'Rollie Fingers',
    accept: ['rollie fingers', 'fingers'],
    era: '1968–1985',
    clues: ['Signature handlebar mustache', 'Ohio-born reliever', 'Oakland dynasty closer', 'Three straight championships', '1981 AL MVP and Cy Young', 'Early relief-ace trophy pioneer', 'All-time saves record at retirement, 341 career saves'],
  },
  {
    id: 'gossage',
    name: 'Goose Gossage',
    accept: ['goose gossage', 'gossage', 'rich gossage'],
    era: '1972–1994',
    clues: ['Intimidating high-90s fastball', 'Distinctive mustache and glare', 'Colorado native', 'Yankees fireman role', 'Multi-inning closer usage', 'Goose nickname', '1978 pennant race heroics, 310 career saves'],
  },
  {
    id: 'sutter',
    name: 'Bruce Sutter',
    accept: ['bruce sutter', 'sutter'],
    era: '1976–1988',
    clues: ['Popularized a signature pitch', 'Split-finger fastball master', 'Pennsylvania native', 'Cubs breakout reliever', 'Later a Cardinals closer', '1979 NL Cy Young', 'Pioneered a long deferred-money contract, 300 career saves'],
  },
  {
    id: 'hoffman',
    name: 'Trevor Hoffman',
    accept: ['trevor hoffman', 'hoffman'],
    era: '1993–2010',
    clues: ['Drafted as a shortstop', 'Converted to pitcher in the minors', 'San Diego closer for over a decade', 'Devastating changeup specialist', 'Entrance song was Hell\'s Bells', 'First to reach 500 saves', 'Held the career saves record with 601'],
  },
  {
    id: 'biggio',
    name: 'Craig Biggio',
    accept: ['craig biggio', 'biggio'],
    era: '1988–2007',
    clues: ['Started his career as a catcher', 'Moved to second base', 'Long Island native', 'Houston franchise lifer', 'Modern hit-by-pitch record holder', 'Half of a beloved Astros duo', '3,000-hit club, twenty seasons with one team'],
  },
  {
    id: 'bagwell',
    name: 'Jeff Bagwell',
    accept: ['jeff bagwell', 'bagwell'],
    era: '1991–2005',
    clues: ['Unusual wide crouching stance', 'Massachusetts roots', 'Traded away from Boston as a prospect', 'Houston first baseman', '1991 NL Rookie of the Year', 'Half of a beloved Astros duo', '1994 NL MVP in a shortened season, 449 career homers'],
  },
  {
    id: 'nomar',
    name: 'Nomar Garciaparra',
    accept: ['nomar garciaparra', 'garciaparra', 'nomar'],
    era: '1996–2009',
    clues: ['Elaborate batting-glove ritual', 'California-born shortstop', 'First name is his father\'s spelled backward', 'Boston shortstop star', 'Part of a famous shortstop trio', '1997 AL Rookie of the Year', 'Traded away before a title year, two batting titles'],
  },
  {
    id: 'walker',
    name: 'Larry Walker',
    accept: ['larry walker', 'walker'],
    era: '1989–2005',
    clues: ['Almost pursued hockey instead', 'Canadian-born outfielder', 'Strong throwing arm', 'Montreal debut', 'Colorado slugger', 'Thin-air power numbers debated', '1997 NL MVP, three batting titles'],
  },
  {
    id: 'rice',
    name: 'Jim Rice',
    accept: ['jim rice', 'rice'],
    era: '1974–1989',
    clues: ['Right-handed power hitter', 'Reputation for immense bat strength', 'South Carolina native', 'Boston left fielder', 'Feared middle-of-the-order bat', 'Whole career with one team', '1978 AL MVP, 382 career homers'],
  },
  {
    id: 'beltre',
    name: 'Adrián Beltré',
    accept: ['adrian beltre', 'beltre'],
    era: '1994–2018',
    clues: ['Debuted as a teenager', 'Elite defensive third baseman', 'Dominican-born third baseman', 'Seattle power-spike season', 'Texas Rangers cornerstone', 'Disliked having his head touched', '3,000-hit club, 477 career homers'],
  },
  {
    id: 'mauer',
    name: 'Joe Mauer',
    accept: ['joe mauer', 'mauer'],
    era: '2004–2018',
    clues: ['Left-handed line-drive hitter', 'Rare batting-title run for a catcher', 'Minnesota-born catcher', 'Hometown Twins draft pick', '2009 AL MVP', 'Concussions forced a position change', 'Three career batting titles, finished at first base'],
  },
  {
    id: 'mattingly',
    name: 'Don Mattingly',
    accept: ['don mattingly', 'mattingly', 'donnie baseball'],
    era: '1982–1995',
    clues: ['Left-handed contact and power hitter', 'Slick defensive glove work', 'Indiana native', 'Yankees first baseman', 'Donnie Baseball nickname', '1985 AL MVP', 'Named team captain, back injury slowed his peak'],
  },
  {
    id: 'acuna',
    name: 'Ronald Acuña Jr.',
    accept: ['ronald acuna jr', 'ronald acuna', 'acuna'],
    era: '2018–present',
    clues: ['Explosive leadoff power', 'Elite speed threat', 'Venezuelan outfielder', 'Atlanta rookie sensation', '2018 NL Rookie of the Year', 'ACL injury interruption', '40 homers and 70 steals in one year, unanimous MVP season'],
  },
  {
    id: 'soto',
    name: 'Juan Soto',
    accept: ['juan soto', 'soto'],
    era: '2018–present',
    clues: ['Elite plate discipline', 'Signature batting-stance shuffle', 'Dominican-born hitter', 'Washington debut as a teenager', '2019 World Series champion', 'Traded from Washington to San Diego', 'Later played in the Bronx, record-setting free agent contract'],
  },
  {
    id: 'speaker',
    name: 'Tris Speaker',
    accept: ['tris speaker', 'speaker', 'the grey eagle'],
    era: '1907–1928',
    clues: ['Played a shallow center field', 'Dead-ball era star', 'Texas-born center fielder', 'Traded from Boston to Cleveland', 'Player-manager for a champion', 'Second all-time in hits at retirement', 'All-time doubles record holder, 3,514 career hits'],
  },
];

// Rotation order for the daily puzzle — deliberately shuffled, not alphabetical
// or grouped by era, so difficulty varies day to day. Extend this list (and
// PLAYERS above) to grow the rotation before it repeats.
const DAILY_ORDER = [
  'mantle', 'gehrig', 'bonds', 'ozzie', 'gwynn', 'thome', 'ryan', 'chipper',
  'ortiz', 'wagner', 'mays', 'betts', 'koufax', 'pedro', 'jeter', 'musial',
  'maddux', 'arod', 'williams', 'trout', 'griffey', 'bench', 'rose', 'fernando',
  'ichiro', 'schmidt', 'ruth', 'harper', 'johnson', 'pujols', 'ripken', 'eckersley',
  'jackson', 'degrom', 'rivera', 'clemens', 'robinson', 'yount', 'aaron', 'boggs',
  'young', 'kershaw', 'mathewson', 'judge', 'hornsby', 'manny', 'berra', 'freeman',
  'clemente', 'thomas', 'paige', 'puckett', 'joshgibson', 'ohtani', 'henderson', 'murray',
  'brett', 'guerrero', 'pudge', 'bobgibson', 'seaver', 'piazza', 'molitor', 'sosa',
  'mcgwire', 'verlander', 'scherzer', 'cabrera', 'posey', 'larkin', 'smoltz', 'glavine',
  'sandberg', 'acuna', 'walker', 'fingers', 'mauer', 'winfield', 'speaker', 'bagwell',
  'nomar', 'killebrew', 'soto', 'campanella', 'palmer', 'gossage', 'dawson', 'beltre',
  'snider', 'carlton', 'ford', 'hoffman', 'kaline', 'yaz', 'rice', 'mattingly',
  'mccovey', 'sutter', 'banks', 'biggio', 'feller', 'spahn',
];
