// Player data for Dinger. Each clue ladder runs vaguest → most revealing.
// Clues never contain any part of the player's own name.
const PLAYERS = [
  {
    id: 'bonds',
    name: 'Barry Bonds',
    accept: ['barry bonds', 'bonds'],
    era: '1986–2007',
    clues: ['California slugger', 'Famous baseball family', 'Started in Pittsburgh', 'Left field star', 'Seven MVP awards', 'Many intentional walks', 'Single-season homer record', '73 home runs', 'All-time home run leader', '762 career homers'],
  },
  {
    id: 'ruth',
    name: 'Babe Ruth',
    accept: ['babe ruth', 'ruth', 'the bambino'],
    era: '1914–1935',
    clues: ['Baltimore childhood', 'Started as pitcher', 'Left-handed slugger', 'Sold by Boston', 'Yankees legend', 'Called shot lore', 'Sultan of Swat nickname', 'Bambino nickname', '714 career homers', 'Number 3 pinstripes'],
  },
  {
    id: 'aaron',
    name: 'Hank Aaron',
    accept: ['hank aaron', 'henry aaron', 'aaron', 'hammerin hank'],
    era: '1954–1976',
    clues: ['Born in Mobile', 'Braves icon', 'Right field power', 'Milwaukee and Atlanta', 'Faced hate mail', 'Hammer nickname', 'Passed 714', 'Hit number 715', '755 career homers', 'Longtime home run king'],
  },
  {
    id: 'jeter',
    name: 'Derek Jeter',
    accept: ['derek jeter', 'jeter', 'the captain'],
    era: '1995–2014',
    clues: ['Michigan roots', 'Yankees draft pick', 'Shortstop leader', 'October regular', 'Famous flip play', 'Dive into stands', 'Team captain', 'Pinstripe icon', '3,000-hit club', 'Number 2 retired'],
  },
  {
    id: 'rivera',
    name: 'Mariano Rivera',
    accept: ['mariano rivera', 'rivera', 'mo', 'the sandman'],
    era: '1995–2013',
    clues: ['Panama native', 'Relief pitcher', 'Yankees closer', 'One famous pitch', 'Cutter master', 'Enter Sandman', 'Postseason legend', 'Only unanimous Hall pick', '652 career saves', 'Last player wearing 42'],
  },
  {
    id: 'griffey',
    name: 'Ken Griffey Jr.',
    accept: ['ken griffey jr', 'ken griffey', 'griffey', 'junior', 'the kid'],
    era: '1989–2010',
    clues: ['Born in Donora', 'Father played MLB', 'Backward cap', 'Sweet lefty swing', 'Seattle superstar', 'Center field wall catches', 'The Kid nickname', 'Reds later career', '630 career homers', 'Number 24 Mariners icon'],
  },
  {
    id: 'ripken',
    name: 'Cal Ripken Jr.',
    accept: ['cal ripken jr', 'cal ripken', 'ripken', 'the iron man'],
    era: '1981–2001',
    clues: ['Maryland roots', 'Orioles lifer', 'Tall shortstop', 'Moved to third base', 'Iron Man nickname', 'Consecutive games streak', 'Passed Gehrig', '2,131 celebration lap', '2,632 straight games', 'Number 8 in Baltimore'],
  },
  {
    id: 'ryan',
    name: 'Nolan Ryan',
    accept: ['nolan ryan', 'ryan', 'the ryan express'],
    era: '1966–1993',
    clues: ['Texas fireballer', 'Very long career', 'Fastball legend', 'Express nickname', 'Played for Astros', 'Famous headlock fight', 'Seven no-hitters', 'Most career strikeouts', '5,714 strikeouts', 'Number 34 power arm'],
  },
  {
    id: 'mays',
    name: 'Willie Mays',
    accept: ['willie mays', 'mays', 'the say hey kid'],
    era: '1951–1973',
    clues: ['Alabama roots', 'Negro leagues start', 'Giants center fielder', 'Say Hey nickname', 'Polo Grounds star', 'Famous over-the-shoulder catch', '1954 World Series catch', '660 career homers', 'Number 24 legend', 'One of baseballs greatest players'],
  },
  {
    id: 'mantle',
    name: 'Mickey Mantle',
    accept: ['mickey mantle', 'mantle', 'the mick', 'the commerce comet'],
    era: '1951–1968',
    clues: ['Oklahoma hometown', 'Switch-hitting slugger', 'Yankees center fielder', 'Knee injuries', 'The Mick nickname', 'Commerce Comet', '1956 Triple Crown', '536 career homers', 'Number 7 pinstripes', 'Yankees dynasty star'],
  },
  {
    id: 'williams',
    name: 'Ted Williams',
    accept: ['ted williams', 'williams', 'teddy ballgame', 'the splendid splinter'],
    era: '1939–1960',
    clues: ['Military pilot', 'Loved fishing', 'Red Sox left fielder', 'Splendid Splinter nickname', 'Teddy Ballgame nickname', 'Defenses shifted against him', 'Last .400 hitter', '.406 season', '521 career homers', 'Number 9 in Boston'],
  },
  {
    id: 'robinson',
    name: 'Jackie Robinson',
    accept: ['jackie robinson', 'robinson', 'jackie'],
    era: '1947–1956',
    clues: ['Georgia birthplace', 'UCLA athlete', 'Army court-martial', 'Signed by Branch Rickey', 'Brooklyn Dodger', 'Rookie of the Year', 'Broke color barrier', 'Home plate steal', 'Number 42 retired', 'MLB celebrates his day'],
  },
  {
    id: 'koufax',
    name: 'Sandy Koufax',
    accept: ['sandy koufax', 'koufax'],
    era: '1955–1966',
    clues: ['Brooklyn lefty', 'Dodgers ace', 'Big curveball', 'Dominant 1960s peak', 'Yom Kippur decision', 'Four no-hitters', 'Perfect game', 'Three Cy Youngs', 'Retired young', 'Number 32 Dodgers legend'],
  },
  {
    id: 'rose',
    name: 'Pete Rose',
    accept: ['pete rose', 'rose', 'charlie hustle'],
    era: '1963–1986',
    clues: ['Cincinnati icon', 'Switch hitter', 'Headfirst slides', 'Charlie Hustle nickname', 'Big Red Machine', 'Player-manager', 'Lifetime ban', 'Passed Ty Cobb', '4,256 career hits', 'MLB hit king'],
  },
  {
    id: 'jackson',
    name: 'Reggie Jackson',
    accept: ['reggie jackson', 'jackson', 'mr october'],
    era: '1967–1987',
    clues: ['Oakland slugger', 'Right field power', 'Big strikeout totals', 'Yankees star', 'Had a candy bar named after him', 'Mr. October nickname', 'Three homers in one Series game', '1977 World Series hero', '563 career homers', 'Number 44 power bat'],
  },
  {
    id: 'ortiz',
    name: 'David Ortiz',
    accept: ['david ortiz', 'ortiz', 'big papi', 'papi'],
    era: '1997–2016',
    clues: ['Dominican slugger', 'Started with Twins', 'Red Sox designated hitter', 'Big Papi nickname', 'Fenway favorite', '2004 curse breaker', 'Postseason grand slams', 'World Series MVP', '541 career homers', 'Number 34 in Boston'],
  },
  {
    id: 'johnson',
    name: 'Randy Johnson',
    accept: ['randy johnson', 'johnson', 'the big unit'],
    era: '1988–2009',
    clues: ['Very tall pitcher', 'Left-handed ace', 'Mariners breakout', 'Diamondbacks champion', 'Devastating slider', 'Hit a bird with a pitch', 'Perfect game', 'Big Unit nickname', '4,875 strikeouts', 'Number 51 fireballer'],
  },
  {
    id: 'maddux',
    name: 'Greg Maddux',
    accept: ['greg maddux', 'maddux', 'the professor', 'mad dog'],
    era: '1986–2008',
    clues: ['Known for glasses', 'Command specialist', 'Started with Cubs', 'Braves rotation star', 'Professor nickname', 'Mad Dog nickname', 'Four straight Cy Youngs', '18 Gold Gloves', '355 career wins', 'Master of painting the corners'],
  },
  {
    id: 'gwynn',
    name: 'Tony Gwynn',
    accept: ['tony gwynn', 'gwynn', 'mr padre'],
    era: '1982–2001',
    clues: ['College basketball player', 'San Diego lifer', 'Padres right fielder', 'Contact hitting master', 'Studied video constantly', 'Eight batting titles', '.338 career average', '3,000-hit club', 'Mr. Padre nickname', 'Number 19 retired'],
  },
  {
    id: 'ichiro',
    name: 'Ichiro Suzuki',
    accept: ['ichiro suzuki', 'ichiro', 'suzuki'],
    era: '2001–2019',
    clues: ['Japanese star', 'Orix beginning', 'Seattle arrival', 'Right field defense', 'Slap-hitting style', 'Rookie and MVP same year', '262-hit season', 'Laser throws', '3,000 MLB hits', 'Single-name legend'],
  },
  {
    id: 'gehrig',
    name: 'Lou Gehrig',
    accept: ['lou gehrig', 'gehrig', 'the iron horse'],
    era: '1923–1939',
    clues: ['Columbia student', 'Yankees first baseman', 'Murderers Row bat', 'Iron Horse nickname', 'Consecutive games streak', 'Luckiest man speech', 'ALS connection', '2,130 straight games', 'Number 4 retired', 'Played beside Ruth'],
  },
  {
    id: 'wagner',
    name: 'Honus Wagner',
    accept: ['honus wagner', 'wagner', 'the flying dutchman'],
    era: '1897–1917',
    clues: ['Dead-ball era star', 'Pirates shortstop', 'Bowlegged runner', 'Flying Dutchman nickname', 'Eight batting titles', 'Inaugural Hall class', 'Famous T206 card', '3,420 career hits', 'Pittsburgh legend', 'Early shortstop great'],
  },
  {
    id: 'young',
    name: 'Cy Young',
    accept: ['cy young', 'young'],
    era: '1890–1911',
    clues: ['19th-century pitcher', 'Cleveland Spiders', 'Right-handed workhorse', 'Cyclone nickname', 'Played for Boston too', 'Perfect game', 'Award named after him', 'Most career wins', '511 victories', 'Pitching trophy namesake'],
  },
  {
    id: 'mathewson',
    name: 'Christy Mathewson',
    accept: ['christy mathewson', 'mathewson', 'big six'],
    era: '1900–1916',
    clues: ['Bucknell athlete', 'New York Giants ace', 'Known as a gentleman', 'Fadeaway pitch', 'Three shutouts in 1905 Series', 'World War I service', 'Inaugural Hall class', '373 career wins', 'Big Six nickname', 'Dead-ball pitching icon'],
  },
  {
    id: 'hornsby',
    name: 'Rogers Hornsby',
    accept: ['rogers hornsby', 'hornsby', 'rajah'],
    era: '1915–1937',
    clues: ['Cardinals star', 'Second baseman', 'Fiery personality', 'Rajah nickname', 'Two Triple Crowns', '.424 season', '.358 career average', 'Seven batting titles', 'St. Louis hitting great', 'Right-handed batting legend'],
  },
  {
    id: 'musial',
    name: 'Stan Musial',
    accept: ['stan musial', 'musial', 'stan the man'],
    era: '1941–1963',
    clues: ['Pennsylvania-born hitter', 'Cardinals icon', 'Outfielder and first baseman', 'Left-handed line-drive hitter', 'The Man nickname', 'Three MVP awards', 'Seven batting titles', '3,630 career hits', '1,815 home and road hits', 'Number 6 in St. Louis'],
  },
  {
    id: 'berra',
    name: 'Yogi Berra',
    accept: ['yogi berra', 'berra', 'yogi'],
    era: '1946–1965',
    clues: ['Yankees catcher', 'Famous quotes', 'Great catcher and manager', 'Managed both New York teams', 'Caught a perfect game', 'Leaped into Larsen arms', 'Ten World Series rings', 'Number 8 retired', 'It aint over line', 'Hall of Fame backstop'],
  },
  {
    id: 'bench',
    name: 'Johnny Bench',
    accept: ['johnny bench', 'bench'],
    era: '1967–1983',
    clues: ['Oklahoma catcher', 'Cincinnati star', 'Big Red Machine', 'Rookie of the Year', 'One-handed catching style', 'Huge hands', 'Two MVP awards', 'Ten Gold Gloves', '389 career homers', 'Number 5 Reds legend'],
  },
  {
    id: 'clemente',
    name: 'Roberto Clemente',
    accept: ['roberto clemente', 'clemente'],
    era: '1955–1972',
    clues: ['Puerto Rican star', 'Pirates right fielder', 'Powerful throwing arm', 'Four batting titles', 'Humanitarian legacy', 'Nicaragua relief flight', 'Plane crash death', 'Exactly 3,000 hits', 'Number 21 icon', 'Pittsburgh legend'],
  },
  {
    id: 'paige',
    name: 'Satchel Paige',
    accept: ['satchel paige', 'paige'],
    era: '1926–1965',
    clues: ['Negro leagues pitcher', 'Kansas City Monarchs', 'Showman style', 'Hesitation pitch', 'Famous age mystery', 'Cleveland MLB debut', 'Oldest MLB rookie', 'Pitched in his fifties', 'Hall of Fame pioneer', 'Ageless pitching legend'],
  },
  {
    id: 'joshgibson',
    name: 'Josh Gibson',
    accept: ['josh gibson'],
    era: '1930–1946',
    clues: ['Negro leagues slugger', 'Catcher with huge power', 'Homestead Grays', 'Pittsburgh Crawfords', 'Called Black Babe Ruth', 'Legendary long homers', 'Died young', 'Posthumous Hall selection', 'MLB records updated later', 'Negro leagues home run legend'],
  },
  {
    id: 'henderson',
    name: 'Rickey Henderson',
    accept: ['rickey henderson', 'henderson', 'man of steal'],
    era: '1979–2003',
    clues: ['Oakland speedster', 'Leadoff hitter', 'Talked in third person', 'Athletics superstar', 'Man of Steal nickname', 'All-time runs leader', '130 steals in a season', '1,406 career steals', 'Greatest base stealer', 'Number 24 Athletics icon'],
  },
  {
    id: 'brett',
    name: 'George Brett',
    accept: ['george brett', 'brett'],
    era: '1973–1993',
    clues: ['Royals lifer', 'Third baseman', 'Left-handed hitter', 'Sweet swing', '.390 chase', 'Pine tar game', 'Home run reinstated', '1985 champion', '3,154 career hits', 'Number 5 in Kansas City'],
  },
  {
    id: 'schmidt',
    name: 'Mike Schmidt',
    accept: ['mike schmidt', 'schmidt'],
    era: '1972–1989',
    clues: ['Phillies third baseman', 'Power and defense', 'Booed by home fans', 'Ten Gold Gloves', 'Three MVP awards', '548 career homers', '1980 champion', 'Greatest third baseman debates', 'Number 20 in Philly', 'Longtime Philadelphia slugger'],
  },
  {
    id: 'ozzie',
    name: 'Ozzie Smith',
    accept: ['ozzie smith', 'the wizard'],
    era: '1978–1996',
    clues: ['Cardinals shortstop', 'Defensive wizard', 'Backflip entrance', 'The Wizard nickname', '13 Gold Gloves', '1985 walk-off homer', 'Switch hitter', 'Number 1 in St. Louis', 'Hall of Fame glove', 'Acrobatic shortstop icon'],
  },
  {
    id: 'boggs',
    name: 'Wade Boggs',
    accept: ['wade boggs', 'boggs'],
    era: '1982–1999',
    clues: ['Red Sox third baseman', 'Contact hitter', 'Chicken routine', 'Superstitious reputation', 'Later Yankee champion', 'Horseback victory lap', '.328 career average', '3,010 hits', 'Number 26 in Boston', 'Left-handed batting champ'],
  },
  {
    id: 'thomas',
    name: 'Frank Thomas',
    accept: ['frank thomas', 'the big hurt'],
    era: '1990–2008',
    clues: ['Auburn athlete', 'Football background', 'White Sox slugger', 'Designated hitter and first base', 'Big Hurt nickname', 'Back-to-back MVPs', 'Huge on-base numbers', '521 career homers', 'Number 35 in Chicago', 'Massive right-handed hitter'],
  },
  {
    id: 'chipper',
    name: 'Chipper Jones',
    accept: ['chipper jones', 'chipper'],
    era: '1993–2012',
    clues: ['Braves third baseman', 'Switch hitter', 'First overall pick', 'Atlanta dynasty piece', 'Crushed Mets pitching', '1999 MVP', '468 career homers', 'Number 10 in Atlanta', 'Larry was real first name', 'Hall of Fame switch bat'],
  },
  {
    id: 'clemens',
    name: 'Roger Clemens',
    accept: ['roger clemens', 'clemens', 'the rocket'],
    era: '1984–2007',
    clues: ['Texas power pitcher', 'Red Sox ace', 'Rocket nickname', '20-strikeout games', 'Blue Jays rebound', 'Yankees and Astros years', 'Famous Piazza incident', 'Seven Cy Youngs', '354 career wins', 'Steroid-era controversy'],
  },
  {
    id: 'pedro',
    name: 'Pedro Martinez',
    accept: ['pedro martinez', 'martinez', 'pedro'],
    era: '1992–2009',
    clues: ['Dominican ace', 'Small frame', 'Expos breakout', 'Red Sox legend', 'Yankee Stadium chant', 'Famous Zimmer incident', 'Three Cy Youngs', '1999 All-Star dominance', '2000 ERA 1.74', 'Number 45 in Boston'],
  },
  {
    id: 'arod',
    name: 'Alex Rodriguez',
    accept: ['alex rodriguez', 'a-rod', 'arod'],
    era: '1994–2016',
    clues: ['Seattle shortstop', 'First overall pick', 'Rangers mega-contract', 'Yankees third baseman', 'A-Rod nickname', 'Biogenesis suspension', '2009 champion', 'Three MVP awards', '696 career homers', 'Number 13 slugger'],
  },
  {
    id: 'manny',
    name: 'Manny Ramirez',
    accept: ['manny ramirez', 'ramirez', 'manny'],
    era: '1993–2011',
    clues: ['Cleveland slugger', 'Red Sox left fielder', 'Quirky personality', 'Unpredictable superstar persona', 'Green Monster home runs', '2004 curse breaker', 'High-five cutoff play', 'Steroid suspension', '555 career homers', 'Postseason RBI machine'],
  },
  {
    id: 'thome',
    name: 'Jim Thome',
    accept: ['jim thome', 'thome'],
    era: '1991–2012',
    clues: ['Cleveland power bat', 'First baseman and DH', 'Gentle reputation', 'Pointed bat before pitches', 'Very high strikeouts', 'Played for five teams', '612 career homers', 'Hall of Fame slugger', 'Number 25 in Cleveland', 'Left-handed home run hitter'],
  },
  {
    id: 'pujols',
    name: 'Albert Pujols',
    accept: ['albert pujols', 'pujols', 'the machine'],
    era: '2001–2022',
    clues: ['Dominican-born slugger', 'Cardinals first baseman', 'The Machine nickname', 'Three MVP awards', '2006 champion', 'Angels contract', 'Returned to St. Louis', '703 career homers', '3,000-hit club', 'Number 5 Cardinals legend'],
  },
  {
    id: 'guerrero',
    name: 'Vladimir Guerrero',
    accept: ['vladimir guerrero', 'guerrero', 'vlad'],
    era: '1996–2011',
    clues: ['Dominican right fielder', 'Expos star', 'Free-swinging hitter', 'Huge throwing arm', 'Often batted gloveless', 'Angels MVP season', 'Famous bad-ball hitter', '2004 AL MVP', 'Cannon arm reputation', 'Vlad nickname'],
  },
  {
    id: 'pudge',
    name: 'Ivan Rodriguez',
    accept: ['ivan rodriguez', 'pudge', 'pudge rodriguez'],
    era: '1991–2011',
    clues: ['Puerto Rican catcher', 'Texas Rangers star', 'Elite throwing arm', 'Pudge nickname', '1999 MVP', 'Marlins champion', '13 Gold Gloves', 'Most games caught', 'Number 7 Rangers icon', 'Hall of Fame catcher'],
  },
  {
    id: 'fernando',
    name: 'Fernando Valenzuela',
    accept: ['fernando valenzuela', 'valenzuela', 'fernando'],
    era: '1980–1997',
    clues: ['Mexican lefty', 'Dodgers phenomenon', 'Looked skyward during delivery', 'Screwball specialist', 'Rookie-year craze', 'Rookie of the Year', 'Cy Young same season', '1981 champion', 'Number 34 in Los Angeles', 'Cultural baseball icon'],
  },
  {
    id: 'trout',
    name: 'Mike Trout',
    accept: ['mike trout', 'trout'],
    era: '2011–present',
    clues: ['New Jersey hometown', 'Angels center fielder', 'Five-tool star', 'Loves weather reports', 'Limited playoff appearances', 'Three MVP awards', 'Number 27', 'Generational WAR totals', 'Millville Meteor nickname', 'Modern center field superstar'],
  },
  {
    id: 'kershaw',
    name: 'Clayton Kershaw',
    accept: ['clayton kershaw', 'kershaw'],
    era: '2008–present',
    clues: ['Dallas lefty', 'Dodgers ace', 'Big curveball', 'Regular-season dominance', 'Postseason scrutiny', 'Charity work in Zambia', 'Three Cy Youngs', '2014 MVP', '2020 champion', 'Number 22 in Los Angeles'],
  },
  {
    id: 'ohtani',
    name: 'Shohei Ohtani',
    accept: ['shohei ohtani', 'ohtani'],
    era: '2018–present',
    clues: ['Japanese two-way star', 'Angels debut', 'Pitcher and hitter', 'Compared to Ruth', 'Unanimous MVP seasons', 'Dodgers mega-deal', 'Famous dog named Decoy', '50-50 season', 'Number 17 superstar', 'Modern two-way phenomenon'],
  },
  {
    id: 'judge',
    name: 'Aaron Judge',
    accept: ['aaron judge', 'judge'],
    era: '2016–present',
    clues: ['Very tall outfielder', 'Yankees right fielder', 'Towering home runs', 'Right-field fan section', 'Team captain', 'Chased Roger Maris', '62-homer season', 'AL home run record', 'Number 99', 'Bronx power star'],
  },
  {
    id: 'betts',
    name: 'Mookie Betts',
    accept: ['mookie betts', 'betts', 'mookie'],
    era: '2014–present',
    clues: ['Tennessee athlete', 'Red Sox right fielder', 'Elite bowler', '2018 MVP', 'Boston champion', 'Blockbuster Dodgers trade', 'Moved to shortstop', 'Leadoff power', 'Number 50 star', 'Modern five-tool star'],
  },
  {
    id: 'harper',
    name: 'Bryce Harper',
    accept: ['bryce harper', 'harper'],
    era: '2012–present',
    clues: ['Teen cover star', 'Nationals phenom', 'Chosen One label', 'Flashy eye black', 'Right field power', 'Two MVP awards', 'Phillies leader', 'Moved to first base', 'Number 3 in Philadelphia', 'Lefty slugger with swagger'],
  },
  {
    id: 'freeman',
    name: 'Freddie Freeman',
    accept: ['freddie freeman', 'freeman'],
    era: '2010–present',
    clues: ['Canadian roots', 'Braves first baseman', 'Left-handed hitter', '2020 MVP', 'Emotional Atlanta exit', 'Dodgers star', 'World Series grand slam', 'High-average power bat', 'Number 5 in Los Angeles', 'Friendly first-base star'],
  },
  {
    id: 'degrom',
    name: 'Jacob deGrom',
    accept: ['jacob degrom', 'degrom'],
    era: '2014–present',
    clues: ['Former college shortstop', 'Mets right-hander', 'Long hair era', 'Little run support', 'Back-to-back Cy Youngs', 'Historically low ERA peak', 'Rangers contract', 'Injury interruptions', '100-mph starter', 'Two-time Cy Young ace'],
  },
  {
    id: 'puckett',
    name: 'Kirby Puckett',
    accept: ['kirby puckett', 'puckett'],
    era: '1984–1995',
    clues: ['Minnesota center fielder', 'Stocky build', 'Beloved Twin', 'Explosive hitter', 'Two World Series titles', '1991 walk-off homer', 'Glaucoma ended career', 'Number 34 in Minnesota', 'Hall of Fame outfielder', 'Game 6 hero'],
  },
  {
    id: 'yount',
    name: 'Robin Yount',
    accept: ['robin yount', 'yount'],
    era: '1974–1993',
    clues: ['Milwaukee Brewer', 'Debuted at 18', 'Started at shortstop', 'Moved to outfield', 'Quiet superstar', 'MVP at two positions', '3,142 career hits', 'Number 19 in Milwaukee', 'Two-time MVP', 'Brewers franchise icon'],
  },
  {
    id: 'murray',
    name: 'Eddie Murray',
    accept: ['eddie murray', 'murray', 'steady eddie'],
    era: '1977–1997',
    clues: ['Orioles first baseman', 'Switch hitter', 'Steady nickname', 'Quiet superstar', 'Later Dodgers and Mets', '500-homer club', '3,000-hit club', '504 career homers', 'Number 33 in Baltimore', 'Durable RBI machine'],
  },
  {
    id: 'eckersley',
    name: 'Dennis Eckersley',
    accept: ['dennis eckersley', 'eckersley', 'eck'],
    era: '1975–1998',
    clues: ['Started as starter', 'Threw a no-hitter', 'Converted to closer', 'Oakland Athletics star', 'Low three-quarter delivery', 'Gave up 1988 World Series homer', '1992 MVP and Cy Young', '390 career saves', 'Eck nickname', 'Hall of Fame closer'],
  },
  {
    id: 'bobgibson',
    name: 'Bob Gibson',
    accept: ['bob gibson'],
    era: '1959–1975',
    clues: ['Omaha native', 'Cardinals ace', 'Also played basketball', 'Harlem Globetrotters link', 'Intimidating mound presence', '1968 pitching season', '1.12 ERA', 'Two Cy Youngs', 'Number 45 in St. Louis', 'Fierce right-handed legend'],
  },
];

// Rotation order for the daily puzzle — deliberately shuffled, not alphabetical
// or grouped by era, so difficulty varies day to day. Extend this list (and
// PLAYERS above) to grow the rotation before it repeats.
const DAILY_ORDER = [
  'mantle', 'gehrig', 'bonds', 'ozzie', 'gwynn', 'thome', 'ryan', 'chipper',
  'ortiz', 'wagner', 'mays', 'betts', 'koufax', 'pedro', 'jeter', 'musial',
  'maddux', 'arod', 'williams', 'trout', 'griffey', 'bench', 'rose', 'fernando',
  'ichiro', 'schmidt', 'ruth', 'harper', 'johnson', 'pujols', 'ripken', 'eckersley',
  'jackson', 'degrom', 'rivera', 'clemens', 'robinson', 'yount', 'aaron', 'boggs',
  'young', 'kershaw', 'mathewson', 'judge', 'hornsby', 'manny', 'berra', 'freeman',
  'clemente', 'thomas', 'paige', 'puckett', 'joshgibson', 'ohtani', 'henderson', 'murray',
  'brett', 'guerrero', 'pudge', 'bobgibson',
];
